window.config = {
  forbidai: [],
  forbidai_user: [],
  forbidall: [],
  forbidboss: [],
  forbidthreecard: [],
  zhinang_tricks: [],
  all: {
    sgscharacters: [],
    sgscards: [],
    sgsmodes: ["hs_hearthstone"],
    stockmode: ["hs_hearthstone"],
    stockextension: [],
    layout: ["default", "newlayout"],
    theme: ["woodden", "music", "simple"],
    card_font: ["xiaozhuan", "huangcao", "caoshu", "xingshu"],
    image_background_filter: [
      "default",
      "blur",
      "gray",
      "sepia",
      "invert",
      "saturate",
      "contrast",
      "hue",
      "brightness",
    ],
  },

  game: "sgs",
  duration: 500,
  hoveration: 1000,
  cheat: false,
  volumn_background: 8,
  volumn_audio: 8,

  config_menu: true,
  auto_popped_config: true,
  auto_popped_history: false,
  auto_skill: true,
  auto_confirm: true,
  enable_drag: true,
  enable_pressure: false,
  pressure_taptic: true,
  hover_handcard: true,
  hover_all: true,
  right_info: true,
  longpress_info: true,
  long_info: true,
  background_music: "music_default",
  background_audio: true,
  background_speak: true,
  glow_phase: "yellow",
  die_move: "flip",

  skin: {},
  gameRecord: {},
  extensionInfo: {},
  autoskilllist: [],
  hiddenModePack: [],
  hiddenCharacterPack: [],
  hiddenCardPack: [],
  hiddenPlayPack: [],
  hiddenBackgroundPack: [],
  customBackgroundPack: [],
  favouriteCharacter: [],
  favouriteMode: [],
  recentIP: [],
  brokenFile: [],

  max_loadtime: "20000",
  theme: "simple",
  layout: "nova",
  cardback_style: "liusha",
  card_style: "default",
  cardshape: "default",
  hp_style: "glass",
  menu_style: "music",
  player_border: "slim",
  radius_size: "reduce",

  image_character: "default",
  image_background: "ol_bg",

  asset_image: true,
  asset_font: true,

  card_font: "xiaozhuan",
  show_statusbar_ios: "off",
  show_statusbar_android: false,
  show_name: true,
  show_replay: false,
  show_round_menu: true,
  show_pause: true,
  show_auto: true,
  show_volumn: true,
  show_cardpile: true,
  only_fullskin: true,
  show_wuxie: false,
  show_wuxie_self: true,
  show_stat: true,
  show_playerids: true,
  show_scrollbar: false,
  mousewheel: true,
  fold_card: true,
  threed_card: false,
  vertical_scroll: false,
  handcard_scroll: 0,
  animation: true,
  skill_animation_type: "default",
  paused: false,
  title: false,
  button_press: true,
  damage_shake: true,
  log_highlight: true,

  modeconfig: false,
  gameconfig: false,
  appearence: false,
  video: "20",

  intro: "i",
  right_click: "pause",
  sort: "type_sort",

  cards: [],
  characters: [],
  moderned_chracters: [],
  moderned_modes: [],
  plays: [],
  extensions: ["炉石普通"],
  banned: [],
  bannedcards: [],
  forbidlist: [],
  bannedpile: {},
  customcardpile: {},
  addedpile: {},

  mode: "hs_hearthstone",
  mode_config: {
    global: {
      player_number: 8,
      auto_identity: "off",
      save_progress: true,
      free_choose: true,
      swap: true,
      change_identity: true,
      battle_number: 3,
    },
  },
  current_mode: {},
  customforbid: [],
  forbid: [],
};
